// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianApprovalReview } from "./GuardianApprovalReview";
import type { GuardianApprovalReviewAction } from "./GuardianApprovalReviewAction";

/**
 * [UNSTABLE] Guardian review state attached to a reviewed thread item so the
 * item lifecycle can be replayed through `thread/read` and `thread/resume`.
 */
export type GuardianApprovalReviewState = { review: GuardianApprovalReview, action: GuardianApprovalReviewAction, };
