// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSourceKind } from "./ThreadSourceKind";

export type ThreadLoadedListParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null, 
/**
 * Optional page size; defaults to no limit.
 */
limit?: number | null, 
/**
 * Optional provider filter; when set, only loaded threads whose current
 * model provider matches one of these values are returned. When present
 * but empty, includes all providers.
 */
modelProviders?: Array<string> | null, 
/**
 * Optional source filter; when set, only loaded threads from these source
 * kinds are returned. When omitted or empty, defaults to interactive
 * sources.
 */
sourceKinds?: Array<ThreadSourceKind> | null, 
/**
 * Optional cwd filter; when set, only loaded threads whose session cwd
 * exactly matches this path are returned.
 */
cwd?: string | null, };
