use super::*;

#[path = "embedded_tests_v2_restore_fail_closed_restore_mutations_inject_items.rs"]
mod embedded_tests_v2_restore_fail_closed_restore_mutations_inject_items;

#[path = "embedded_tests_v2_restore_fail_closed_restore_mutations_name_set.rs"]
mod embedded_tests_v2_restore_fail_closed_restore_mutations_name_set;

#[path = "embedded_tests_v2_restore_fail_closed_restore_mutations_memory_mode.rs"]
mod embedded_tests_v2_restore_fail_closed_restore_mutations_memory_mode;
